
on:
  push:
    branches:
      - main
name: 🚀 Upload to Hadawatha.lk on Push Main
jobs:
  web-deploy-1:
    name: 🎉 ByHeart-live
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: 📂 Hadwatha LK files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.hwth_ftp_server }}
          username: ${{ secrets.hwth_ftp_username }}
          password: ${{ secrets.hwth_ftp_password }}
          local-dir: ./
          server-dir: /web/platform/plugins/onepay-lk
          exclude: |
            **/.git*
            **/.git*/**

      - name: 📂 By heart files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.byht_ftp_server }}
          username: ${{ secrets.byht_ftp_username }}
          password: ${{ secrets.byht_ftp_password }}
          local-dir: ./
          server-dir: /web/platform/plugins/onepay-lk
          exclude: |
            **/.git*
            **/.git*/**